project:
  type: website
  output-dir: docs
image: RayPatagonia.png
date-modified: last-modified

website:
  navbar:   
    title: Raymond B. Huey  
    right:
      - text: "home"
      - href: index.qmd
      - text: "CV"
      - href: Huey2023_CV.pdf
      - text: "Publications"
      - href: Publications.qmd
      - text: "For prospective students"
      - href: prospective_students.qmd
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

