---
title: "For prospective students and postdocs"
---
I am no longer accepting new graduate students or postdocs. However, my views of how to be a grad student are summarized in a article (below) that I wrote in response to one by Steve Stearns (below). Our presentations were originally given in the fall of 1976 as coordinated, back-to-back "seminars" at Ecolunch, a weekly seminar/discussion group at the University of California, Berkeley. We handed out typed outlines of our presentations. These notes made it into the graduate student grave-vine and were distributed widely in subsequent years. Peter Morin eventually encouraged us to write them up for publication. We did so in the Bulletin of the Ecological Society of America. As Steve noted once, these articles — not our scientific studies — are undoubtedly our most widely read papers!

In any case, the two papers make a complementary duo - and I recommend reading both. If I were to add anything to them now, I would add advice I learned from Eric Pianka, my own (unofficial) MA advisor and long-term colleague and friend. Namely, when you set out on your graduate career, your goal should be nothing less than becoming *the* established authority in some area by the time you complete your degree. That may sound ambitious. But if you aim high, you will hit high.

I have attached a link to a related paper "*On becoming a better scientist*." This was an invited paper, based on a talk at a graduate-student organized symposium (2011) at the Institute for Dryland Environmental Research Ecology, Ben Gurion University. It is basically a reflective essay. In part, I look back on "Stearns and Huey." And in part, I look at lessons I learned later in my career. I end with the challenge of how to stay fresh during a long career in science.

[Steve Stearns - Some Modest Advice for Graduate Students](https://faculty.washington.edu/hueyrb/pdfs/advice.pdf)

[Ray Huey - Reply to Stearns: Some Acynical Advice for Graduate Students](https://faculty.washington.edu/hueyrb/pdfs/reply.pdf)

[Ray Huey - On becoming a better scientist](https://faculty.washington.edu/hueyrb/PDFAug2013/OnBetterScience2011.pdf)