---
title: "Publications"
---
200) Huey, R. B. and D. B. Miles. 2022. Signatures of geography, climate, and foliage on given names of baby girls. Evolutionary Human Sciences 4, E56.  https://doi:10.1017/ehs.2022.53
199) Huey, R. B., and L.B. Buckley. 2022. Designing a seasonal acclimation study presents challenges and opportunities.  Integrative Organismal Biology 4: obac016. https://doi.org/10.1093/iob/obac016.
198) Buckley, L.B., R. B. Huey, and J. G. Kingsolver. 2021. Asymmetry of thermal sensitivity and the thermal risk of climate change.  Global Ecology and Biogeography 31:2231-2244. https://doi.org/10.1111/geb.13570
197)  Huey, R.B., D. B. Miles, and E. R. Pianka. 2021. Seasonality in Kgalagadi lizards: inferences from legacy data. The American Naturalist 198:759-771. https://doi.org/10.1086/716895.
196) Sillero, N., R. B. Huey, G. Gilchrist, L. Rissler, and M. Pascual. 2020. Distribution modelling of an introduced species: do adaptive genetic markers affect potential range? Proceedings of the Royal Society B 287:2020179120201791. http://dx.doi.org/10.1098/rspb.2020.1791.
195) Kearney, M. R., W. P. Porter, and R. B. Huey. 2020.  Modelling the joint effects of body size and microclimate on heat budgets and foraging opportunities of ectotherms. Methods in Ecology and Evolution 12: 458-467. https://doi.org/10.1111/2041-210X.
194) Huey, R. B., L. Ma, O. Levy, and M. R. Kearney. 2020 Three questions about the eco-physiology of overwintering underground.  Ecology Letters 24:170-185. https://doi.org/10.1111/ele.13636
193) Huey, R. B., and M. R. Kearney. 2020. PERSPECTIVE: Dynamics of death by heat.  Science 369:1163-1163.  https://doi.org/10.1126/science.abe0320  
192)  Huey, R. B., and P. R. Grant. 2020. COMMENTARY: Lizards, toepads, and the ghost of hurricanes past. Proceedings of the National Academy of Sciences USA 117:11194-11196.
191)  Huey, R. B., C. Carroll, R. Salisbury, and J.-L. Wang. 2020. Mountaineers on Mount Everest:  Effects of age, sex, experience, and crowding on rates of success and death. PLoS ONE15(8): e0236919. https://doi.org/10.1371/journal.pone.0236919
190)  Huey, R. B., and J. G. Kingsolver. 2019.  Climate warming, resource availability, and the metabolic meltdown of ectotherms. The American Naturalist 194:E140–E150.
189)  Huey, R. B., T. Garland, Jr., and M. Turelli. 2019.  Revisiting a key innovation in evolutionary biology:  Felsenstein’s ‘Phylogenies and the Comparative Method.’  The American Naturalist 193:755–772.
188)  Deutsch, C.A., J. J. Tewksbury, M. Tigchelaar, D. S. Battisti, S. C. Merrill, R. B. Huey, and R. L. Naylor. 2018. Increase in crop losses to insect pests in a warming climate. Science 361:916-919.
187) Huey, R. B., L. B. Buckley, and W. Du. 2018. Biological buffers and the impact of climate change.  Integrative Zoology 13:349-354.
186)  Aburto-Oropeza, O., et al. 2018. Harnessing cross-border resources to confront climate change. Environmental Science and Policy 878:128-132.
185)  Huey, R. B. and C. R. Tracy. 2018. In Memorium:  James Edward Heath.  Physiological and Biochemical Zoology 91:834-836.
184) Sheldon, K.A., R. B. Huey, M. Kaspari, and N. J. Sanders.  2018.  Fifty years of mountain passes; a perspective on Dan Janzen’s classic paper. The American Naturalist 191:553-565.
183)  Ma, L., L. B. Buckley, R. B. Huey, and W.-G. Du. 2018 A global test of the cold-climate hypothesis for the evolution of viviparity.  Global Ecology and Biogeography 2018:1-11.
182)  Huey, R. B. and E. R. Pianka. 2017. Body temperature distributions of active diurnal lizards in three deserts: skewed up or skewed down? Functional Ecology 2017:1-11. Doi: 10.1111/1365-2435.12966. 
181) Grant, P. R., B. R. Grant, R. B. Huey, M. C. Johnson, A. H. Knoll, and J. Schmitt. 2017. Evolutionary responses to extreme events. Philosophical Transactions B Royal Society 372:20160146.
180)  Sinclair, B. J., K. E. Marshall, M. A. Sewell, D. L. Levesque, C. S. Willett, S. Slotsbo, Y. Dong, D. G. Harley, D. J. Marshall, B. S. Helmuth, R. B. Huey. 2016. Can we predict ectotherm responses to climate change using thermal performance curves and body temperatures? Ecology Letters 19:1372-1285.
179)  Huey, R. B. and C. Deutsch.  2016.  PERSPECTIVE:  How Frigatebirds soar around the Doldrums. Science 353:26-27.
178) Buckley, L. B. and R. B. Huey. 2016. Temperature extremes: geographic patterns, recent changes, and implications for organismal vulnerabilities. Global Change Biology doi: 10.1111/gcb.13313.
177) Buckley, L. B. and R. B. Huey. 2016. How extreme temperatures impact organisms and the evolution of their thermal tolerance. Integrative and Comparative Biology 56:98-109.
176) Deutsch, C., A. Ferrel, H.-O. Pörtner, and R. B. Huey. 2015. Climate change tightens a metabolic constraint on marine habitat. Science 348:1132-1135.
175) Otero, L. M., R. B. Huey, and G. C. Gorman. 2015. A few meters matter: Local habitats drive reproductive cycles in a tropical lizard. American Naturalist 186:E72-E80.
174) Castilla, A. M., R. B. Huey, J. J. Calvete, R. Richer, and A. H. M. Al-Hemaidi. 2015. Arid environments: Opportunities for studying co-evolutionary patterns of scorpion venoms in predator-prey systems. Journal of Arid Environments 112:165-169. 
174) Sunday, J. M., A. E. Bates, M. R. Kearney, R. K. Colwell, N. K. Dulvy, J. T. Longino, and R. B. Huey. 2014. Thermal-safety margins and the necessity of thermoregulatory behavior across latitude and elevation. Proceedings of the National Academy of Sciences USA 111: 5610-5615. 
173) Huey, R. B., and P. J. Landrigan. 2012. Epigenetic synthesis: a need for a new paradigm for evolution in a contaminated world. F1000Prime Recommendation of [Crews D and Gore AC, F1000 Biol Rep 2012, 4(18)]. In F1000Prime, 02 Oct 2012; DOI: 10.3410/f.717957733.793462153. 
172) Hertz, P. E., Y. Arima, A. Harrison, R. B. Huey, J. B. Losos, and R. E. Glor. 2013. Asynchronous evolution of physiology and morphology in Anolis lizards. Evolution, 67:2101-2113. 
171) Huey, R. B., M. R. Kearney, A. Krockenberger, J. A. M. Holtum, M. Jess, and S. E. Williams 2012. Predicting organismal vulnerability to climate warming: roles of behaviour, physiology and adaptation. Philosophical Transactions of the Royal Society B 367:1665-1679.
170) Dillon, M. E., R. Liu, G. Wang, and R. B. Huey. 2012. Disentangling thermal preference and the thermal dependence of motion in ectotherms. Journal of Thermal Biology 37:631-639.
169) Huey, R. B. 2011. On becoming a better scientist. Israel Journal of Ecology and Evolution 57:293-307.
168) Huey, R. B., and J. G. Kingsolver. 2011. COMMENTARY: Variation in universal temperature dependence of biological rates. Proceedings of the National Academy of Sciences USA 108:10377-10378.
167) Falkowski, P. G., T. Algeo, L. Codispoti, C. A. Deutsch, Emerson, B. Hales, R. Huey, W. Jenkins, L. R. Kump, L. Levin, T. Lyons, N. Nelson, O. Schofield, R. Summons, L. Talley, E. Thomas, F. Whitney, and C. Pilcher. 2011. Ocean deoxygenation: past, present, and future. EOS 92:409-420.
166) Anderson, J. L., L. Albergotti, R. B. Huey, and P.C. Phillips. 2011. Does thermoregulatory behavior maximize reproductive fitness of natural isolates of Caenorhabditis elegans? BMC Evolutionary Biology 22:257. doi: 10.1186/1471-2148-11-157
165) Gibert, P., R. Allemand, H. Henri and R. B. Huey. 2010. Local adaptation and evolution of parasitoid interactions in an invasive species, Drosophila subobscura. Evolutionary Ecology Research 12: 873–883.
164) Dillon, M. E., G. Wang, and R. B. Huey. 2010. Global metabolic impacts of recent climate warming. Nature 467:704-706.
163) Huey, R. B., J. B. Losos, and C. Moritz. 2010. PERSPECTIVE: Are lizards toast? Science 328: 832-833.
162) Angilletta, M. J. Jr., R. B. Huey, and M. Frazier. 2010. Thermodynamic effects on organismal performance: Is hotter better? Physiological and Biochemical Zoology 83:197-206.
161) Huey, R. B.2010. Evolutionary physiology of insect thermal adaptation to cold environments. pp. 223-241 in: Low Temperature Biology of Insects, eds. D.L. Denlinger and R. E. Lee, Jr. Cambridge University Press, Cambridge.
160) Huey, R. B. 2009. Natural history observations on Henry Fitch. Herpetological Review 40:399.
159) Balanyà, J. , R. B. Huey, G. W. Gilchrist, L. Serra. 2009. The chromosomal polymorphism of Drosophila subobscura: a microevolutionary weapon to monitor global change. Heredity 103:364-367. doi. 10.1038/hdy.2009.86
158) Dillon, M. E., G. Wang, P.A. Garrity, and R. B. Huey. 2009. Thermal preference in Drosophila. Journal of Thermal Biology 34:109-119.
157) Huey, R. B., and F. Rosenzweig. 2009. Laboratory evolution meets Catch 22: balancing simplicity and realism. pp. 671-707 in: Experimental Evolution: Concepts, Methods, and Applications (T. Garland, Jr., and M. R. Rose, eds). University of California Press, Berkeley.
156) Huey, R. B., and M. Pascual. 2009. Partial thermoregulatory compensation by a rapidly evolving invasive species along a latitudinal cline. Ecology 90:1715-1720.
155) Huey, R. B., and J. J. Tewksbury. 2009. COMMENTARY: Can behavior douse the fire of climate warming? Proceedings of the National Academy of Sciences USA 106:3647-3648 (doi:10.1073/pnas.0900934106)
154) Huey, R. B., J. J. Tewksbury, C. A. Deutsch, L. J. Vitt, P. E. Hertz, and H. J. Álvarez Pérez 2009. Why tropical forest lizards are vulnerable to climate warming. Proceedings of the Royal Society, B 276:1939-1948 doi:10.1098/rspb.2008.1957. 
153) Mestres, F. J. Balanyà, M. Pascual, C. Arenas, G. W. Gilchrist, R. B. Huey, and L. Serra  2009. Evolution of Chilean colonizing populations of Drosophila subobscura: lethal genes and chromosomal arrangements. Genetica 136:37-48. doi:10.1007/s10709-008-9298-y.153)
152) Gilchrist, G. W., L. M. Jeffers, B. West, D. G. Folk, J. Seuss, and R. B. Huey. 2008. Clinal patterns of desiccation and starvation resistance in ancestral and invading populations of Drosophila subobscura. Evolutionary Applications 1:513-523.
151) Huey, R. B., and F. J. Janzen. 2008. COMMENTARY: climate warming and environmental sex determination in tuatara: the Last of the Sphenodontians. Proceedings of the Royal Society B 275:2181-2183.
150) Huey, R. B., and A. F. Bennett. 2008. Bart’s familiar quotations: the enduring biological wisdom of George A. Bartholomew. Physiological and Biochemical Zoology 81:519-525.
149) Tewksbury, J. J., R. B. Huey, and C.A. Deutsch. 2008. PERSPECTIVE:  Putting the heat on tropical animals. Science 320:1296-1297.
148) Kingsolver, J. G., and R. B. Huey. 2008. Size, temperature, and fitness: three rules. Evolutionary Ecology Research 10:251-268.
147) Crozier, L. G., A.P. Hendry, P. W. Lawson, T. P. Quinn, N. J. Mantua, J. Battin, R.G. Shaw, and R. B. Huey. 2008. Potential responses to climate change for organisms with complex life histories: evolution and plasticity in Pacific salmon. Evolutionary Applications 1:252-270.
146) Deutsch, C. A., J. J. Tewksbury, R. B. Huey, K. S. Sheldon, C. K. Ghalambor, D. C. Haak, and P. R. Martin. 2008. Impacts of climate warming on terrestrial ectotherms across latitude. Proceedings of the National Academy of Science, USA 105:6668-6672.
145) Martin, T. L., and R. B. Huey. 2007. Why “suboptimal” is optimal: Jensen’s inequality and ectotherm thermal preferences. American Naturalist 171:E102-E118.
144) Anderson, J. L., L. Albergotti, S. Proulx, C. Peden, R. B. Huey, and P. C. Phillips. 2007. Thermal preference of Caenorhabditis elegans: a null model and empirical tests. Journal of Experimental Biology 210:3107-3116.
143) Huey, R. B., R. Salisbury, J.-L. Wang, and M. Mao 2007. Effects of age and gender on success and death of mountaineers on Mount Everest. Biology Letters 3:498-500.
142) Dillon, M. E., L. R. Y. Cahn, and R. B. Huey. 2007. Fitness consequences of temperature transients in Drosophila melanogaster. Journal of Experimental Biology 210:2897-2904.
141) Huey, R. B., and E. R. Pianka. 2007. Lizard thermal biology: do genders differ? American Naturalist 170:473-478.
140) Pascual, M., M.P. Chapuis, F. Mestres, J. Balanyà, R. B. Huey, G.W. Gilchrist, L. Serra, and A. Estoup. 2007. Introduction history of Drosophila subobscura in the New World: a microsatellite based survey using ABC methods. Molecular Ecology 16:3069-3083. 
139) Huey, R. B., and E. R. Pianka. 2007. Historical introduction: On widely foraging for Kalahari lizards. pp. 1 – 10 in: The Foraging biology of lizards: evolutionary consequences of foraging mode. S.M. Reilly, L. D. McBrayer, and D. B Miles, eds. Cambridge University Press, Cambridge, U.K. 
138) Balanyá, B., J. M. Oller, R. B. Huey, G. W. Gilchrist, and L. Serra. 2007. Response to Comment on “Global Genetic Change Tracks Global Climate Warming in Drosophila subobscura”. Science 315:1497.
137) Huey, R. B., and G. W. Gilchrist. 2006. Drosophila subobscura. In: Invasive Species of the Pacific Northwest. P. D Boersma, S. E. Reichard, and A. Van Buren, eds. University of Washington Press, Seattle.
136). Huey, R. B., B. Moreteau, J.C. Moreteau, P. Gibert, G. W. Gilchrist, A. R. Ives, T. Garland, Jr., and J. R. David 2006. Sexual size dimorphism in a Drosophila clade, the D. obscura group. Zoology 109:318-330.
135) Frazier, M., R. B. Huey, and D. Berrigan. 2006. Thermodynamics constrains the evolution of insect population growth rates: “warmer is better.” American Naturalist 168:512-520.
134) Balanyá, J., J. M. Oller, R. B. Huey, G. W. Gilchrist, and L. Serra. 2006. Global genetic change tracks global climate warming in Drosophila subobscura. Science 313:1773-1775.
133) Dudley, R., R. B. Huey, and D. R. Carrier. 2006. Living history of physiology: Carl Gans. Advances in Physiological Education 30:102-107.
132) Ghalambor, C. K., R. B. Huey P. R. Martin, J. J. Tewksbury, and G. Wang. 2006. Are mountain passes higher in the tropics? Janzen’s hypothesis revisited. Integrative and Comparative Biology 46:5-17.
131) Huey, R. B., and E. R. Pianka. 2005. Review: Almuth D. Schmidt. 2004. Die Mimikry zwischen Eidechsen und Laufkafern. Herpetological Review 36:347-348.
130) Hibbitts, T. J., E. R. Pianka, R. B. Huey, and M.J. Whiting. 2005. Ecology of the common barking gecko (Ptenopus garrulus) in Southern Africa. Journal of Herpetology 39:509-515.
129) Huey, R. B., and P. D. Ward. 2005. Climbing a Triassic Mt. Everest: Into thinner air. Journal of the American Medical Association 295:1761-1762.
128) Huey, R. B., G. W. Gilchrist, and A. P. Hendry. 2005. Using invasive species to study evolution. pp. 139-164 in: Species invasions: insights to ecology, evolution and biogeography, D. F. Sax, S. D. Gaines and J. J. Stachowicz, eds. Sinauer Associates, Sunderland, MA.
127) Huey, R. B., and G. E. Hofmann. 2005. Introduction: a symposium honoring George A. Bartholomew. Integrative and Comparative Biology 45:217-218.
126) Huey, R. B., and P. D. Ward. 2005. Hypoxia, global warming, and terrestrial Late Permian extinctions. Science 308:398-401.
125) Gilchrist, G. W., and R. B. Huey. 2004. Plastic and genetic variation in wing loading as a function of temperature within and among parallel clines in Drosophila subobscura. Integrative and Comparative Biology 44:461-470.
124) Huey, R. B., J. Suess, H. Hamilton, and G. W. Gilchrist 2004. Starvation resistance in Drosophila melanogaster: testing for a possible ‘cannibalism’ bias. Functional Ecology 18:952-954.
123) Gilchrist, G. W., R. B. Huey, J. Balanyà, M. Pascual, and L. Serra. 2004. A time series of evolution in action: Latitudinal cline in wing size in South American Drosophila subobscura. Evolution 58:768-780. 
122) Huey, R. B.2003. 2002 Sewall Wright Award: Linda Partridge. American Naturalist 161:i– ii.
121) Massot, M., R. B. Huey, J. Tsuji, and F. H. van Berkum. 2003. Genetic, prenatal, and postnatal correlates of dispersal in hatchling fence lizards (Sceloporus occidentalis). Behavioral Ecology 14:650-655.
120) Huey, R. B., J. Balanya and F. Mestres. 2003. Detection of yellow mutation in North American Drosophila subobscura. Drosophila Information Service 86:173. 
119) Kingsolver, J. G., Huey, R. B.2003. Introduction: the evolution of morphology, performance, and fitness. Integrative and Comparative Biology 43:361-366.
118) Huey, R. B., G. W. Gilchrist, K. Ward, L. Maves, D. Pepin, and D. Houle 2003. Mutation, performance, fitness. Integrative and Comparative Biology 43:387-395.
117) Huey, R. B., and R. Salisbury. 2003. Success and death on Mount Everest. American Alpine Journal. [The complete paper is accessible at the AAC website.]
116) David, J. R., P. Gibert, B. Moreteau, G. W. Gilchrist, and R. B. Huey. 2003. The fly that came in from the cold: geographic variation of recovery time from low-temperature exposure in Drosophila subobscura. Functional Ecology 17:425-430.
115) Balanyà, J., L. Serra, G. W. Gilchrist, R. B. Huey, M. Pascual, F. Mestres, and E. Solé. 2003. Evolutionary pace of chromosomal polymorphism in colonizing populations of Drosophila subobscura: an evolutionary time series. Evolution 57:1837-1845.
114) Huey, R. B., P. E. Hertz and B. Sinervo. 2003. Behavioral drive versus behavioral inertia in evolution: a null model approach. American Naturalist 161:357-366.
113) Moreteau, B., P. Gibert, G. Pétavy, J.-C. Moreteau, R. B. Huey, and J. R. David. Morphometrical evolution in a Drosophila clade: the Drosophila obscura group. Journal of Zoological Systematics and Evolution 41:64-71.
112) Huey, R. B. and W. J. Moody. 2002. PERSPECTIVE: Snake sodium channels resist TTX arrest. Science 297:1289-1290.
111) Huey, R. B., M. Carlson, L. Crozier, M. Frazier, H. Hamilton, C. Harley, A. Hoang, and J. G. Kingsolver 2002. Plants versus animals: do they deal with stress in different ways? Integrative and Comparative Biology 42:415-423.
110) Huey R. B., Eguskitza X, and Dillon M. 2001. Mountaineering in thin air. pp. 225-236 in Hypoxia: From Genes to the Bedside, Advances in Experimental Medicine and Biology (502). R. C. Roach, P. D. Wagner, and P. H. Hackett (eds.) New York: Kluwer/Plenum Academic. 
109) Huey, R. B, and X. Eguskitza. 2001. Limits to human performance: elevated risks on high mountains. Journal of Experimental Biology 204:3115-3119.
108) Huey, R. B., and D. Berrigan. 2001. Temperature, demography, and ectotherm fitness. American Naturalist 158:204-210.
107) Huey, R. B. 2001. The economics of adventure: on the high cost of Himalayan climbing permits. The Alpine Journal 106:155-169.
106) Gilchrist, G. W., R. B. Huey, and L. Serra. 2001. Rapid evolution of wing size clines in Drosophila subobscura. Genetica 112-113:273-286.
105) Gibert, P., and R. B. Huey. 2001. Chill-coma temperature in Drosophila: effects of development temperature, latitude, and phylogeny. Physiological and Biochemical Zoology 74:429-434.
105) Gilchrist, G. W., and R. B. Huey. 2001. Parental and developmental temperature effects on the thermal dependence of fitness in Drosophila melanogaster. Evolution 55:209-214.
103) Gilbert, P., R. B. Huey, and G. W. Gilchrist. 2001. Locomotor performance of Drosophila melanogaster: interactions among developmental and adult temperatures, age, and geography. Evolution 55:205-209.
102) Huey, R. B., E. R. Pianka and L. J. Vitt. 2001. How often do lizards ‘run on empty’? Ecology 82:1-7.
101) Feder, M. E., A. F. Bennett, and R. B. Huey. 2000. Evolutionary physiology. Annual Reviews of Ecology and Systematics 31:315-341.
100) Huey, R. B., and X. Eguskitza. 2000. Supplemental oxygen and death rates on Everest and K2. Journal of the American Medical Association 284:181. [A non-technical version was published in the Year 2000 American Alpine Journal.]
98) Kari, J. R., and R. B. Huey. 2000. Size and seasonal temperature in free-ranging Drosophila subobscura. Journal of Thermal Biology 25:267-272.
98) Huey, R. B., G.W. Gilchrist, M. Carlsen, and L. Serra 2000. Rapid evolution of a latitudinal cline in body size in an introduced fly. Science 287:308-309.
97) Hertz, P. E., R. B. Huey, and R. D. Stevenson. 1999.  Temperature regulation in free-ranging ectotherms:  what are the appropriate questions? African Journal of Herpetology 48:41-48. 
96) Huey, R. B., D. Berrigan, G. W. Gilchrist, and J. C. Herron. 1999. Testing the adaptive significance of acclimation: a strong inference approach. American Zoologist 39:323-336.
95) Gilchrist, G. W., and R. B. Huey. 1999. The direct response of Drosophila melanogaster to selection on knock-down temperature. Heredity 83:15-29.
94) Kingsolver, J. G., and R. B. Huey. 1998. Evolutionary analyses of morphological and physiological plasticity in thermally variable environments. American Zoologist 38:545-560. 
93) Gilchrist, G. W., R. B. Huey, and L. Partridge.1997. Thermal sensitivity of Drosophila melanogaster: Evolutionary responses of adults and eggs to laboratory natural selection at different temperatures. Physiological Zoology 70:403-414
92) Werner, Y. L., N. Carrillo de Espinoza, R. B. Huey, D. Rothenstein, A. W. Salas, and F. Videla. 1996. Observations on body temperatures of some Neotropical desert geckos (Reptilia: Sauria: Gekkoninae). Cuadernos de Herpetologia 10:59-70.
91) Huey, R. B., and D. Berrigan.1996. Testing evolutionary hypotheses of acclimation. pp. 205-237, in I. A. Johnston and A. F. Bennett, eds, Animals and Temperature: Phenotypic and Evolutionary Adaptation. Society of Experimental Biology Symposium Volume, Cambridge University Press. 
90) Crill, W. D., R. B. Huey, and G. W. Gilchrist. 1996. Within- and between generation effects of temperature on the morphology and physiology of Drosophila melanogaster. Evolution 50:1205-1218.
89) Lauder, G. V., R. B. Huey, R. K. Monson, and R. J. Jensen. 1995. Systematics and the study of organismal form and function. BioScience 45:696-704.
88) Cavicchi, S., D. Guerra, and V. LaTorre Huey, and R. B. Huey. 1995. Chromosomal analysis of heat-shock resistance in Drosophila melanogaster evolving at different temperatures in the laboratory. Evolution 49:676-684. 
87) Huey, R. B., T. Wakefield and W. D. Crill. 1995. Effects of parental, developmental, and laying temperatures on early fecundity of Drosophila melanogaster. Heredity 74:216-223.
86) Zamudio, K., R. B. Huey, and W. D. Crill. 1995. Bigger isn't always better: developmental and parental temperature and male territoriality in Drosophila melanogaster. Animal Behaviour 49:671-677. 
85) Huey, R. B. 1994. Introduction to Evolutionary Ecology Section, pp. 175-182. In: Vitt, L. J. & E. R. Pianka, eds. Lizard Ecology, Princeton University Press.
84) Huey, R. B. 1993. Survival skills. pp. 113-121 in The Cycle of Life: Animal Behavior. T. Halliday, ed. Weldon Russell, Sydney, Australia.
83) Huey, R. B., and J. G. Kingsolver.1993. Evolutionary responses to extreme temperatures in ectotherms. American Naturalist 141:S21-S46.
82) Kareiva, P.M., J. G. Kingsolver, and R. B. Huey. 1993. Biotic Interactions and Global Change. Sinauer Associates, Sunderland, MA. 
81) Kareiva, P.M., J. G. Kingsolver, and R. B. Huey. 1993. An agenda for population and community research in global change. pp. 480-486 in: P. M. Kareiva, J. G. Kingsolver, and R. B. Huey, eds. Biotic Interactions and Global Change. Sinauer Associates, Sunderland, MA.
80) Hertz, P. E., R. B. Huey, and R. D. Stevenson. 1993. How carefully do ectotherms regulate body temperature? The Fallacy of the Inappropriate Question. American Naturalist 142:796-818.
79) Sinervo, B.,P. Doughty, R. B. Huey, and K. Zamudio 1992. Allometric engineering: a causal analysis of natural selection on offspring size. Science 258:1927-1930.
78) Huey, R. B., W. D. Crill, J. G. Kingsolver, and K. E. Weber 1992. A method for rapidly measuring heat or cold resistance of small insects. Functional Ecology 6:489-494.
77) T. Garland, T. Jr., R. B. Huey, and A. F. Bennett 1991. Phylogeny and thermal physiology in lizards: a reanalysis. Evolution 45:1969-1975. 
76) Smith, M. T., and R. B.Huey. 1991. Ether and CO2 affect heat tolerance of Drosophila melanogaster. Drosophila Information Service 70:215.
75) Huey, R. B. 1991. Physiological consequences of habitat selection. American Naturalist 137:S91-S115.
74) Huey, R. B., L. Partridge, and K. Fowler. 1991 Thermal sensitivity of Drosophila melanogaster responds rapidly to laboratory natural selection. Evolution 45:751-756.
73) Shaffer, H. B., C. C. Austin, and R. B. Huey. 1991 The consequences of metamorphosis on salamander (Ambystoma) locomotor performance. Physiological Zoology 64:212-231.
72) Cooper, W. E. Jr., L. J. Vitt, R. Hedges, and R. B. Huey. 1990. Locomotor impairment and defense in gravid lizards (Eumeces laticeps): behavioral shift in activity may offset costs of reproduction in an active forager. Behavioral Ecology and Sociobiology 27:153-157.
71) Sinervo, B., and R. B. Huey. 1990. Allometric engineering: an experimental test of the causes of interpopulational differences in performance. Science 248:1106-1109.
70) Huey, R. B., and J. G. Kingsolver. 1990. Stressing ecology and evolution (book review). Ecology 71:1635-1636.
69) Bennett, A. F., and R. B. Huey. 1990. Studying the evolution of physiological performance. pp. 251-284 in: D. J. Futuyma and J. Antonovics, eds., Oxford Surveys in Evolutionary Biology, Vol. 6. Oxford University Press, Oxford, U.K.
68) Huey, R. B., A. E. Dunham, K. L. Overall, and R. A. Newman 1990. Variation in locomotor performance in demographically known populations of the lizard Sceloporus merriami. Physiological Zoology 63:845-872.
67) Hankins, T. Garland, Jr., and R. B. Huey.1990. Locomotor capacity and social dominance in adult male lizards (Sceloporus occidentalis). Functional Ecology 4:243-250.
66) Huey, R. B., and A. F. Bennett. 1990. Physiological adjustments to fluctuating thermal environments: an ecological and evolutionary perspective. pp. 37-59 in: R. Morimoto, A. Tissieres, and C. Georgopoulous, eds. The Role of Heat Shock and Stress Response in Biology and Human Disease).
65 Huey, R. B., and J. G. Kingsolver. 1989. Evolution of thermal sensitivity of ectotherms. Trends in Ecology and Evolution 4:131-135. .
64) van Berkum, F. H., R. B. Huey, J.S. Tsuji, and T. Garland, Jr.1989. Repeatability of individual differences in locomotor performance and body size during early ontogeny of the lizard Sceloporus occidentalis. Functional Ecology 3:97-105.
63) Huey, R. B. 1989. MacArthur Award--Thomas W. Schoener. ESA Bulletin 70:29-30.
62) Tsuji, J. S., R. B. Huey, F. H. van Berkum, T. Garland, Jr., and R. G. Shaw 1989. Locomotor performance of hatchling fence lizards (Sceloporus occidentalis): quantitative genetics and morphometric correlates. Evolutionary Ecology 3:240-252.
61) Huey, R. B., C. R. Peterson, S. J. Arnold, and W. P. Porter 1989. Hot rocks and not-so-hot rocks: retreat-site selection by garter snakes and its thermal consequences. Ecology 70:931-944.
60) Huey, R. B., P. H. Niewiarowski, J. Kaufmann, and J. C. Herron 1989. Thermal biology of nocturnal gekkos: Is sprint performance maximal at low body temperatures? Physiological Zoology 62:488-504.
59) Hertz, P. E., R. B. Huey, and T. Garland, Jr. 1988. Time budgets, thermoregulation, and maximal locomotor performance: are reptiles Olympians or Boy Scouts? American Zoologist 28:927-938.
58) Gans, C., and R. B. Huey, eds. 1988. Biology of the Reptilia, Vol. 16. (Ecology B: Defense and Life History). A. R. Liss.
57) Huey, R. B.  1987. Reply to Stearns: Some acynical advice for graduate students. Bulletin of the Ecological Society of America 68:150-153.
56) Huey, R. B., and A. F. Bennett.1987. Phylogenetic studies of coadaptation: preferred temperatures versus optimal performance temperatures of lizards. Evolution, 41:1098-1115.
55) Feder, M. E., A. F. Bennett, W. W. Burggren, and R. B. Huey, eds. 1987. New Directions in Ecological Physiology. Cambridge University Press.
54) Huey, R. B. 1987. Phylogeny, history, and the comparative method, pp.76-98 in: M. E. Feder, A. F. Bennett, W. W. Burggren, and R. B. Huey, eds. New Directions in Ecological Physiology, Cambridge University Press.
53) Huey, R. B., and A. E. Dunham. 1987. The repeatability of locomotor performance in natural populations of the lizard Sceloporus merriami. Evolution 41:1116-1120.
52) Garland, T., Jr., and R. B. Huey. 1987. Testing symmorphosis: does structure match functional requirements? Evolution 41:1404-1409.
51) van Berkum, F. H., R. B. Huey, and B. Adams. 1986. Physiological consequences of thermoregulation in a tropical lizard (Ameiva festiva). Physiological Zoology 59:464-472.
50) Huey, R. B. 1986. Thermoregulation in reptiles, pp. 70-71. In T.R. Halliday and K. Adler, eds. Encyclopedia of Amphibians and Reptiles, Equinox (Oxford) Ltd., Oxford.
49) Tracy, C. R., J. S. Turner, and R. B. Huey. 1986. A biophysical analysis of possible thermoregulatory adaptation in sailed pelycosaurs, pp. 195-206. In: N. Hotton, III, P. D. MacLean, J. J. Roth, and E. C. Roth, eds. Ecology and Biology of Mammal-like Reptiles. Smithsonian Institution Press, Washington, D.C. 
48) Huey, R. B. and A. F. Bennett. 1986. A comparative approach to field and laboratory studies in evolutionary ecology. pp. 82-98 in: M.E. Feder and G. Lauder, eds. Predator-Prey Relationships in Lower Vertebrates. University of Chicago Press. 
47) Huey, R. B. and P. E. Hertz. 1984. Effects of body size and slope on acceleration of a lizard (Stellio (Agama) stellio). Journal of Experimental Biology110: 113-123.
46) Bennett, A. F., R. B. Huey, and H. John-Alder 1984. Physiological correlates of natural activity and locomotor capacity in two species of lacertid lizards. Journal of Comparative Physiology 154:113-118.
45) Huey, R. B. and P. E. Hertz. 1984. Is a jack-of-all-temperatures a master of none? Evolution 38:41-50.
44) Nagy, K. A., R. B. Huey, and A. F. Bennett. 1984. Field energetics and foraging mode of Kalahari lacertid lizards. Ecology 65:588-596.
43) Tracy, C. R., F. H. van Berkum, J. S. Tsuji, R. D. Stevenson, J. A. Nelson, and R. B. Huey1984. Errors resulting from linearizations in energy balance equations. Journal of Thermal Biolog, 9:2661-264. 
42) Bennett, A.F., R. B. Huey, H. B. Alder, and K. A. Nagy. 1984. The parasol tail and thermoregulatory behavior of the Cape Ground Squirrel (Xerus inauris). Physiological Zoology 57:57-62.
40) Huey, R. B., E. R. Pianka, and C. M. Cavalier. 1984. Ecology of lizards in the Kalahari Desert, Africa. Research Reports, National Geographic Society 41:365-370.
39) Huey, R. B., E. R. Pianka, and T. W. Schoener, eds. 1983. Lizard Ecology: Studies of a Model Organism. Harvard University Press, Cambridge.
38) Huey, R. B., and E. R. Pianka (with appendix by S. Pimm). 1983. Temporal separation of activity and dietary overlap. pp. 281-290 in: R. B. Huey, E. R. Pianka, and T. W. Schoener, eds. Lizard Ecology: Studies of a Model Organism, Harvard University Press, Cambridge. 
37) Hertz, P. E., R. B. Huey, and E. Nevo. 1983. Homage to Santa Anita: thermal sensitivity of sprint speed in agamid lizards. Evolution 37:1075-1084.
36) Huey, R. B. 1982. Phylogenetic and ontogenetic determinants of sprint performance in some diurnal Kalahari lizards. Koedoe 25:43-48.
35) Huey, R. B. 1982. Temperature, physiology, and the ecology of reptiles. pp. 25-91, In: C. Gans and F. H. Pough, eds., Biology of the Reptilia Vol. 12, Physiology (C). Academic Press, London. 
34) Huey, R. B. 1983. Natural variation in body temperature and physiological performance in a lizard (Anolis cristatellus), pp. 484-490. In: A. G. J. Rhodin and K. Miyata, eds., Advances in Herpetology and Evolutionary Biology: Essays in Honor of Ernest E. Williams. Museum of Comparative Zoology, Cambridge, Mass.
33) Hertz, P. E., R. B. Huey, and E. Nevo. 1982. Fight versus flight: thermal dependence of defensive behaviour in a lizard. Animal Behaviour 30:676-679.
32) Huey, R. B. and P. E. Hertz. 1982. Effects of body size and slope on sprint speed of a lizard (Stellio (Agama) stellio). Journal of Experimental Biology 97:401-409.
31) Huey, R. B., W. Schneier, G. L. Erie, and R. D. Stevenson. 198l. A field-portable racetrack for measuring acceleration and velocity of small cursorial animals. Experentia 37:1356-1357.
30) Huey, R. B., and E. R. Pianka. 1981. Ecological consequences of foraging mode. Ecology 62:991-999.
29) Hertz, P. E., and R. B. Huey. 1981. Compensation for altitudinal changes in the thermal environment by some Anolis lizards on Hispaniola. Ecology 62:515-521.
28) Huey, R. B. 1980. Sprint velocity of tadpoles (Bufo boreas) through metamorphosis. Copeia 1980:537-540.
27) Huey, R. B. 1979. The compleat dictionary of zoology: I. Vernacular words in herpetology. Quarterly Review of Biology 54:301-307.
26) Huey, R. B. 1979. Book review: Biology of the Reptilia, Vol. 7. Ecology and Behaviour A. (C. Gans and D.W. Tinkle, eds.). Quarterly Review of Biology 54:105-106.
25) Huey, R. B., and R. D. Stevenson. 1979. Integrating thermal physiology and ecology of ectotherms: a discussion of approaches. American Zoologist 19:357-366. (
24) Pianka, E. R., R. B. Huey, and L. R. Lawlor. 1979. Niche segregation in desert lizards. pp. 67-115, in Analysis of Ecological Systems, D.J. Horn, R. Mitchell, and G.R. Stairs, Eds. (Ohio State Univ. Press, Columbus). 
23) Huey, R. B. 1979. Parapatry and niche complementarity of Peruvian desert geckos (Phyllodactylus): the ambiguous role of competition. Oecologia (Berl.) 38:249-259.
22) Schoener, T. W., R. B. Huey, and E.R. Pianka. 1979. A biogeographic extension of the compression hypothesis: species in narrow sympatry. American Naturalist 113:295-298.
21) Kim, Y. J., G. C. Gorman, and R. B. Huey. 1978. Genetic variation and differentiation in two species of the fossorial African skink, Typhlosaurus (Sauria: Scincidae). Herpetologica 34:192-194.
20) Pianka, E. R., and R. B. Huey. 1978. Comparative ecology, resource utilization, and niche segregation among gekkonid lizards in the southern Kalahari. Copeia 1978:691-701.
19) Huey, R. B. 1978. Latitudinal pattern of between-altitude faunal similarity: Mountains might be "higher" in the tropics. American Naturalist 112:225-229.
18) Huey, R. B., and E. R Pianka, with appendix by J.A. Hoffman. 1977. Seasonal patterns of thermoregulatory behavior and body temperature of diurnal Kalahari lizards. Ecology 58:1066-1075. 
17) Huey, R. B. and E. R. Pianka. 1977. Patterns of niche overlap among broadly sympatric versus narrowly sympatric Kalahari lizards (Scincidae: Mabuya). Ecology 58:119-128.
16) Huey, R. B. 1977. Egg retention in some high-altitude Anolis lizards. Copeia 1977:373-375.
15) Huey, R. B. and E. R. Pianka. 1977. Natural selection for juvenile lizards mimicking noxious beetles. Science (Wash., D.C.) 195:201-203.
14) Huey, R. B. and T. P. Webster. 1976. Thermal biology of Anolis lizards in a complex fauna: the cristatellus group on Puerto Rico. Ecology 57:985-994.
13) Huey, R. B. and M. Slatkin. 1976. Costs and benefits of lizard thermoregulation. Quarterly Review of Biology 51:363-384.
12) Huey, R. B. and T.P. Webster. 1975.Thermal biology of a solitary lizard: Anolis marmoratus of Guadeloupe, Lesser Antilles. Ecology 56:445-452.
11) Huey, R. B. 1975. A new gecko from Malpelo Island (Sauria: Gekkonidae: Phyllodactylus). Smithsonian Contributions in Zoology 176:44-46.
10) Huey, R. B. and E. R. Pianka. 1974. Ecological character displacement in a lizard. American Zoologist 14:1127-1136.
9) Huey, R. B. 1974. Behavioral thermoregulation in lizards: importance of associated costs. Science (Wash., D.C.) 184:1001-1003.
8) Huey, R. B., E. R. Pianka, M. E. Egan, and L. W. Coons. 1974. Ecological shifts in sympatry: Kalahari fossorial lizards (Typhlosaurus). Ecology 55:304-316.
7) Huey, R. B. 1974. Winter thermal ecology of the iguanid lizard Tropidurus peruvianus. Copeia 1974:l49-l55.
6) Pianka, E. R. and R. B. Huey 1971. Bird species density in the Kalahari and the Australian deserts. Koedoe 14:123-129.
5) Martin, W. F. and R. B. Huey. 1971. The function of the epiglottis in sound production (hissing) of Pituophis melanoleucus. Copeia 197l:752-754.
4) Dixon, J. R. and R. B. Huey. 1970. Systematics of the lizards of the gekkonid genus Phyllodactylus on mainland South America. Los Angeles City Museum Contributions in Science 192:1-78.
3) Huey, R. B. and J. R. Dixon. 1970. A new Pseudogonatodes from Peru with remarks on other species of the genus. Copeia 1970:538-542.
2) Huey, R. B. 1969. Winter diet of the Peruvian desert fox. Ecology 50:1089-1091.
1) Gorman, G. C., R. B. Huey, and E. E. Williams. 1969. Cytotaxonomic studies on some unusual iguanid lizards assigned to the genera Chamaeleolis, Polychrus, Polychroides, and Phenacosaurus with behavioral notes. Breviora, Museum of Comparative Zoology 316:1-17
